name: Minefetch
version: 1.0
author: Azulre
main: io.azulre.minefetch.Main
load: STARTUP
commands:
  neofetch:
    description: Provides a parsed output from fastfetch
    usage: /<command>
  loadfetch:
    description: Provides a LagMeter like output with CPU usage and Memory usage graphs.
    usage: /<command>
